version: "3.8"

services:
  nginx:
    image: nginx
    container_name: Nginx_Dev
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./nginx/conf.d:/etc/nginx/conf.d"
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
      - "./ssl:/ssl"

  db:
    image: mysql
    container_name: MySQL_Dev
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - "./mysql:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: Pas5w0rd*
